# Site Settings
title: Jose Alfredo Alvarez Aldana - Online CV
url: 'http://chepeftw.com'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

plugins:
  - jekyll-minifier

jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

#Profile information
name: Jos√© Alfredo Alvarez Aldana
tagline: DevOps Specialist
pic: me_2.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a DevOps specialist, software architect and computer science researcher.
As a DevOps specialist, based in Paris, I have worked implementing automation pipelines for big infrastructures relying on Terraform and Ansible for AWS, GCP and Azure.
I have worked deploying multiple applications written in Python and Scala, natively and containerized, into different environments relying on CI/CD pipelines.
Lately, I have been focusing on migrations to Kubernetes, implementing efficient log centralization with ELK and also strong monitoring capabilities with Stackdriver, Grafana and Prometheus.
As a software architect, I have worked with multiple web tech implementations focused on infrastructure, back end and front end development. 
With this, I am also experienced in project management, scrum methodologies, SEO and marketing.
I have been lucky to work on site and off site from people from Guatemala, Mexico, the Caribbean, USA, Canada and Europe.
As a researcher, I worked in Telecom SudParis, France, focused on researching distributed monitoring of MANETs.
I have proposed different approaches from decentralized to distributed, and I have developed the necessary tools to prove them.
I developed a NS3 Docker Emulator which has enabled me to re produce accurately thousands of tests in a very short time.
I am an engineer on computer science graduated from Galileo University in Guatemala.
After that I studied a master in information technology with specialization in computer networks and information security.
In search to widen my knowledge, I also studied a second engineering but on electronics. 
I consider myself a highly proactive person and devoted to finish what I start.
I like to do a lot of research, so I can fully understand what I am working on. 
I am very passionate about technology so I try to keep up by reading and studying new technologies and methodologies. 
On a personal level, I consider myself a very responsible person, I believe that it is what best talks about ourselves. 
I really like challenges and I know that I am very adaptable to change.
I always look for the positive things of every situation and try to give the best of me.'

#sidebar links
email: joselfredo1515@gmail.com
phone: +33 06 95 50 74 15
website: chepeftw.com #do not add http://
dblp: Alvarez:Jose
linkedin: chepeftw
github: chepeftw
twitter: '@chepeftw'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-23590276-3

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
